name: My Workflow

on:
  push:
    branches:
      - main  # Chạy khi có commit vào nhánh main

jobs:
  build:
    runs-on: ubuntu-latest  # Sử dụng hệ điều hành Ubuntu

    steps:
      - name: Checkout code  # Bước checkout mã nguồn
        uses: actions/checkout@v2

      - name: Set up JDK 11  # Bước cài đặt JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Thêm các bước thực hiện công việc của bạn ở đây, ví dụ: biên dịch, chạy các bài kiểm tra, triển khai, v.v.
      # Ví dụ:
      - name: Compile and Test  # Bước biên dịch và kiểm tra
        run: |
          javac TestCalculator.java
          java -cp . TestCalculator
