name: Run JUnit Tests

on:
  push:
    branches: [ main ]  # Chạy workflow khi có push vào nhánh main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Bước checkout mã nguồn

      - name: Set up JDK 17  # Bước cài đặt JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build and run JUnit tests
        run: |
          git clone https://github.com/tanlocnguyen151203/csn-da21ttb-nguyentanloc-githubactions-unittest.git  # Clone repository của bạn vào thư mục làm việc
          cd csn-da21ttb-nguyentanloc-githubactions-unittest  # Di chuyển đến thư mục của repository

          # Compile và chạy test JUnit
          javac -cp .:junit-platform-console-standalone-1.10.1.jar TestCalculator.java
          java -jar junit-platform-console-standalone-1.10.1.jar --class-path . --scan-class-path
