name: Run JUnit Tests

on:
  push:
    branches: [ main ]  # Chạy workflow khi có push vào nhánh main

jobs:
  build_and_test:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: src/TestCalculator.java'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
  
  
      - name: Restore dependencies
        run: dotnet restore $SOLUTION
  
      - name: Build
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG
        
      - name: Test
        run: dotnet test $SOLUTION --configuration $BUILD_CONFIG --logger "trx;LogFileName=test-results.trx" || true
        
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: DotNET Tests
          path: "**/test-results.trx"                            
          reporter: dotnet-trx
          fail-on-error: true
